### ISSUE TITLE
Appearance - Start / Link doesn't work.

### ISSUE THREAD

**Issue by Zuntie** [AtlasFw/atlasfw.github.io#3] opened 2022-05-11 20:46 UTC
# Submit a feature request or bug report

Before you submit an issue, check to see if it has already been reported.
Any questions should be directed to team.

---

Replace any "X" below with your information.

## Development environment

- Operating system of serve: Website
- Resource version: Not informed.
- Issue Priority: Medium.

## Current behavior

Include screenshots if possible.

The link doesn't work.
![Image2](https://user-images.githubusercontent.com/60542183/167944677-38c6002e-baee-4503-8a37-b03aeb686d6b.png)
![Image](https://user-images.githubusercontent.com/60542183/167944681-b6a27cb6-85dc-455a-addb-8590cc2a6897.png)

## Expected behavior

Should return some useful information about the Appearance - Start.

## Steps to reproduce

Only fill this in if you are filing a bug report.

1. X

## Other relevant information

I don't think so.

**Comment by BombayV** [comment] 2022-05-11 21:02
The issue is that I linked the old branch. As soon as I get on my computer I’ll change the link.

**Comment by BombayV** [comment] 2022-05-16 09:35
Fixed on latest commit.

**Closed as completed by BombayV** 2022-05-16 09:35 UTC
